Improve documentation titles
altair-viz/altair pull request #2721
Opened 2022-11-18 22:29 UTC by binste

I'd suggest to remove 'Transform' from the titles of the transform pages. The navigation bar looks much cleaner this way, especially now that we also have a page for every mark. This is also in line with the vega-lite docs. There are also two other smaller commits in this PR.

![Screenshot 2022-11-18 at 23 26 35](https://user-images.githubusercontent.com/23366411/202813760-14a61889-fc9c-4b42-bd48-c72f1e769bcb.png)

2022-11-18 23:16 UTC, joelostblom requested changes
Yup I agree that your suggestions makes the navbar cleaner. A couple of minor comments and then we can merge.

2022-11-18 23:16 UTC, joelostblom commented on doc/user_guide/interactions.rst
> +We can create a variable parameter using :func:`alt.param`, and assign that parameter a default value of 0.1 using the ``value`` property, as follows:
I can see that there is a mix of `alt.param` and `parameter` used currently on this page. I think the approach most consistent with the rest of the docs would be to change all these to just say `param`. Could you update all the occurrences of this on the page?

2022-11-18 23:16 UTC, joelostblom commented on doc/user_guide/interactions.rst
> +The above example shows all three elements at work. The :input_dropdown: is :bind: to the :selection: which is called from the :condition: encoded through the data.
It seems like this is not rendering properly in the docs 
![image](https://user-images.githubusercontent.com/4560057/202818504-7781c1e0-7566-428d-8355-91aa939a93bb.png)

2022-11-24 19:04 UTC, binste commented
Thank you for the feedback. I addressed both of your comments.

2022-11-24 19:15 UTC, joelostblom approved these changes
Looks great now, thanks again!

2022-11-24 19:15 UTC, merged