documentation on spatial data
altair-viz/altair pull request #2750
Opened 2022-12-11 22:33 UTC by mattijn

Fix https://github.com/altair-viz/altair/issues/2740.

This PR introduces a different section how to specify data. 

The following sections are defined (each on its own page):
- DataFrame data
- Dictionary data
- URL data
- Spatial data
- Generator data

I only looked carefully to the page on spatial data, the others are merely infrastructure code that can be extened and improved by other PRs.

2022-12-15 05:00 UTC, joelostblom requested changes
Thanks for adding this section! I have some minor comments on wording and adding some links to other doc pages. I saw that you initially added the other data pages as well but then removed them, do you think we should add that (and remove the "specifying data" page) in a separate PR or add it to this one?

2022-12-16 22:46 UTC, mattijn commented on doc/user_guide/data/spatial.rst
> +information of each geometry is stored (``properties``).
Changed to another dataset, one that incudes continents of the world. 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5186265/208201204-a2088e1e-8b1e-4d86-bf5a-e4d1f9648a10.png">

2022-12-16 22:49 UTC, mattijn commented on doc/user_guide/data/index.rst
> +When data is specified as a DataFrame, the encoding is quite simple, as Altair
Agree, but it is the landing page to specify data, so I thought it might be good to have a basic example with the most standard approach as well?

2022-12-16 22:54 UTC, mattijn commented
> I saw that you initially added the other data pages as well but then removed them, do you think we should add that (and remove the "specifying data" page) in a separate PR or add it to this one?

I removed them again since I'd just copy+paste them into the different pages from the existing https://altair-viz.github.io/user_guide/data.html page. I did not yet remove this page, so I though it might probably be better that someone does this in a separate PR. 

Probably good to check as well if these pages needs to be modified or extended.

2022-12-18 02:09 UTC, joelostblom commented on doc/user_guide/data/index.rst
> +When data is specified as a DataFrame, the encoding is quite simple, as Altair
Yes, that's true. I don't feel super strongly about this either way so maybe we can merge this PR as is and address in the upcoming PR that adds the DataFrame page.

2022-12-18 02:13 UTC, joelostblom commented on doc/user_guide/data/spatial.rst
> +information of each geometry is stored (``properties``).
That's such as great example! :raised_hands:

2022-12-18 02:15 UTC, joelostblom approved these changes
This looks great from what I can see! The Altair documentation has gotten SO much better in terms of geographic data with this and the mark_geoshape PR you made earlier. Thank you @mattijn ! Feel free to merge unless you were planning to add something else. I opened https://github.com/altair-viz/altair/issues/2761 for the follow up data sections

2022-12-24 14:55 UTC, merged