Remove vega-v5 wrappers
altair-viz/altair pull request #2822
Opened 2023-01-08 20:52 UTC by mattijn

This PR removes the Vega V5 wrappers from the Altair repository.

It removes them from the generate_schema_wrapper, magics, mimebundle, tests and docs.

Not everything related to vega is removed since the saving utilities requires vega bundles to be included.

2023-01-08 21:42 UTC, mattijn commented
Can you check @joelostblom? I think I removed everything related to the Vega wrapper, but I might have missed some parts in the docs/docstring.

2023-01-09 09:56 UTC, joelostblom requested changes
Nice, thanks for doing this. Apart from one of the deleted tests I think this looks good. I grepped the repo for "vega" and didn't notice any other places needing an update.

I noticed the name of the branch and just wanted to say that I think it makes sense to have a separate PR for removing the old Vega-Lite versions and limiting this PR to Vega as you have done now :+1:

2023-01-09 09:56 UTC, joelostblom commented on tests/utils/tests/test_mimebundle.py
> -
It looks like this vl-convert test was accidentally deleted

2023-01-09 09:57 UTC, joelostblom commented on tests/utils/tests/test_mimebundle.py
> -
Nevermind, I can see that this is only for conversion to the Vega mimebundle now, so it should be deleted

2023-01-09 09:58 UTC, joelostblom approved these changes
I misread the test I thought was accidentally deleted, this looks good.

2023-01-09 13:55 UTC, joelostblom commented
One thing I was thinking here is that maybe we should add an explicit note in the docs that Altair specs can programmatically be turned into VegaLite with `to_json`, but not Vega specs, and then include the way to create Vega specs directly in Jupyter via IPython.display that you mentioned in https://github.com/altair-viz/altair/issues/2817?

2023-01-13 20:59 UTC, closed without merging