Add title section to customization page
altair-viz/altair pull request #2838
Opened 2023-01-16 21:44 UTC by palewire

For #2748 and #2195

2023-01-17 08:01 UTC, joelostblom requested changes
Thanks @palewire ! Could you add the two last examples from https://stackoverflow.com/questions/57244390/how-to-add-a-subtitle-to-an-altair-generated-chart/66147967#66147967 as well?

2023-01-17 08:01 UTC, joelostblom commented on doc/user_guide/customization.rst
> +      title=alt.Title("Iowa's green energy boom", subtitle="A growing share of the state's energy has come from renewable sources")
```suggestion
      title=alt.Title(
          "Iowa's green energy boom",
          subtitle="A growing share of the state's energy has come from renewable sources"
      )
```

2023-01-17 15:27 UTC, palewire commented
Okay. I took a run at that.

2023-01-18 17:15 UTC, joelostblom requested changes
Great, thank you!  Just a few more comments and then we can merge

2023-01-18 17:15 UTC, joelostblom commented on doc/user_guide/customization.rst
> +      title=alt.TitleParams(
```suggestion
      title=alt.Title(
```

2023-01-18 17:15 UTC, joelostblom commented on doc/user_guide/customization.rst
> +The subtitle can run to two lines.
```suggestion
The subtitle can run to two lines by passing a list where each list item is a line (if you don't want to create this list manually as in the example below, you can use the ``wrap`` function from the `textwrap library https://docs.python.org/3/library/textwrap.html`_ to split a string into a list of substrings of a certain length).
```

2023-01-18 17:15 UTC, joelostblom commented on doc/user_guide/customization.rst
> +      title=alt.TitleParams(
```suggestion
      title=alt.Title(
```

2023-01-18 17:15 UTC, joelostblom commented on doc/user_guide/customization.rst
> +      title=alt.TitleParams(
```suggestion
      title=alt.Title(
```

2023-01-18 17:15 UTC, joelostblom commented on tests/examples_methods_syntax/iowa_electricity.py
> +    title=alt.TitleParams("Iowa's green energy boom", subtitle="A growing share of the state's energy has come from renewable sources")
```suggestion
    title=alt.Title(
        "Iowa's green energy boom",
        subtitle="A growing share of the state's energy has come from renewable sources"
    )
```

2023-01-18 17:15 UTC, joelostblom commented on doc/user_guide/customization.rst
> +The parameters object can also `configure <https://altair-viz.github.io/user_guide/configuration.html#config-title>`_ a number of other attributes.
```suggestion
The ``Title`` object can also configure a number of other attributes, e.g., the position of the title and subtitle (see see :ref:`user-guide-customization` for details).
```

2023-01-19 02:40 UTC, palewire commented
I've accepted all your changes

2023-01-19 12:46 UTC, joelostblom approved these changes
Great, thank again!

2023-01-19 12:47 UTC, merged