Deprecating selection
altair-viz/altair pull request #2923
Opened 2023-02-23 20:05 UTC by ChristopherDavisUCI

As requested by @mattijn here: https://github.com/altair-viz/altair/pull/2908#issuecomment-1440698123

Add a deprecation decorator to `selection` and update the usage in a few spots.

2023-02-23 20:33 UTC, joelostblom requested changes
Look good! One minor suggestion.

Do you think we should follow the same path for `alt.binding` for consistency? https://joelostblom.github.io/altair-docs/user_guide/API.html#api-functions

2023-02-23 20:33 UTC, joelostblom commented on altair/vegalite/v5/api.py
> +    Although it is possible to create a point selection using 'selection(type="point")' and an interval selection using 'selection(type="interval")', for consistency, it is recommended to use 'select
```suggestion
   Use 'selection_point()' or 'selection_interval()' instead; these functions also include more helpful docstrings."""
```

2023-02-23 22:44 UTC, ChristopherDavisUCI commented
Good catch @mattijn, I was searching for `type="interval"` instead of `type='interval'`.  Should we always use one or the other, at least for this little case?

2023-02-24 23:41 UTC, mattijn commented
Regarding:

> Do you think we should follow the same path for `alt.binding` for consistency? https://joelostblom.github.io/altair-docs/user_guide/API.html#api-functions

No. Not yet at least. See eg https://github.com/altair-viz/altair/issues/2760, which uses `alt.binding(input='color')`

2023-02-24 23:41 UTC, merged